#
#<!--mcphase.mcphas.ini-->
[MCPHASE RUNTIME CONTROL]
#!nofthreads=1
# to stop program set exit to 1
exit=0

# to hold program set pause to 1
pause=0

# to display all structures while iterating set displayall to 1
# (mind that by using this option mcphas gets very slow)
displayall=0

# to create a logfile of the propagation versus free energy  set logfevsQ to 1
# (mind this uses a lot of disc space)
logfevsQ=0

[XY PHASEDIAGRAM PARAMETERS]
xT=1
xHa=0
xHb=0
xHc=0

# range of x
xmin=1
xmax=1
xstep=5
yT=0
yHa=0
yHb=1
yHc=0

# range of y
ymin=0
ymax=5
ystep=0.2
T0=0
Ha0=0
Hb0=0
Hc0=0
out1=19
out2=20
out3=0
out4=21
out5=1
out6=2
out7=3

[GENERATION OF SPIN CONFIGURATIONS]
hmin=0.5
hmax=0.7
deltah=0.01
kmin=0
kmax=0
deltak=0.001
lmin=0
lmax=0
deltal=0.001
maxqperiod=16
maxnofspins=270
minnr1=1
minnr2=1
minnr3=1

# number of random seed spins  to try for each initial spinconfiguration
nofrndtries=400

# number of Monte Carlos random steps  to try for each spin
nofMCsteps=2000
maxnoftestspincf=4

[PARAMETERS FOR SUB FECALC SELFCONSISTENCY PROCESS]

# maximum number of selfconsistency loops
maxnofmfloops=0

# standard deviation - limit to end selfconsistency process
# standard deviation is defined by ...sta=sqrt(sum_{i=1}^{n} (newmf-old mf)i^2/n)
# the meanfield is given by mf=gj mb H [meV] (gj...lande factor, mb... bohr magneton)
maxstamf=1e-06

# mean field step ratio bigstep( = step to perform /calculated step<1)
# note: if sta increases - then for 10 iterations set step ratio to smallstep=bigstep/n
# by default n=5. However, if bigstep>1 then n=integervalue(bigstep) and step ratio=bigstep-n
bigstep=1

# sum_{i=1}^{n} abs(actual change of angular momentum <Ji> with respect to
# initial  configuration) > maxspinchange will  end selfconsistency process
maxspinchange=60

[OUTPUT OF PHYSICAL PROPERTIES]
nofspincorrs=0
maxnofhkls=0
maxQ=0

