#*********************************************************************
#
# File:          Makefile
#
# Project:       McPhase Tutorial
#
# Description:   Makefile for the program
#
# Author(s):     M. Rotter
#
# Original:	 Nov 2008
#
#**********************************************************************

all: 
	cp ./02fitting/theory.clc.orig ./02fitting/theory.clc  

clean: 
	cp ./02fitting/theory.clc.orig ./02fitting/theory.clc  




