# Parameters for meanfield calculation - module mcphas version 3.0
#<!--mcphase.mcphas.ini-->
#*********************************************************
# mcphas - program to calculate static magnetic properties
# reference: M. Rotter JMMM 272-276 (2004) 481
#**********************************************************
[MCPHASE RUNTIME CONTROL]
# to stop program set exit to 1                   
exit=0                   
# to hold program set pause to 1                   
pause=0                   
# to display all structures while iterating set displayall to 1
# (mind that by using this option mcphas gets very slow)                   
displayall=0                   
# to create a logfile of the propagation versus free energy  set logfevsQ to 1
# (mind this uses a lot of disc space)                   
logfevsQ=0

[XY PHASEDIAGRAM PARAMETERS]
#xy phasediagram axes - parameters
# structures are calculated in the xy - phasediagram                   
# the direction of x and y can be chosen:                       
# vector in (H-T) space corresponding to x axis (xT [K] xHa [T] xHb [T] xHc [T])
xT=1
xHa=0
xHb=0
xHc=0
# range of x
xmin=1
xmax=1

# vector in (H-T) space corresponding to y axis (yT [K] yHa [T] yHb [T] yHc [T])
yT=0
yHa=1
yHb=1
yHc=1
# range of y
ymin=0
ymax=0
ystep=0.5
# offset for phase diagram
T0=0
Ha0=0
Hb0=0
Hc0=0

[GENERATION OF SPIN CONFIGURATIONS]
# test q vector (qmin qmax deltaq)
hmin=0

deltah=0.1
kmin=0

deltak=0.1
lmin=0

deltal=0.1
# maximal periodicity of spinconfigurations generated by q vectors
maxqperiod=10
# maximal number of spins in spinconfigurations generated by q vectors
maxnofspins=24
# number of random (Monte Carlo) spin inversions  to try for each initial spinconfiguration
nofrndtries=0

[PARAMETERS FOR SUB FECALC SELFCONSISTENCY PROCESS]                  
# maximum number of selfconsistency loops
maxnofmfloops=1000
# standard deviation - limit to end selfconsistency process                   
# standard deviation is defined by ...sta=sqrt(sum_{i=1}^{n} (newmf-old mf)i^2/n) 		  
# the meanfield is given by mf=gj mb H [meV] (gj...lande factor, mb... bohr magneton)
maxstamf=7e-5
# mean field step ratio (=actual step/calculated step) to perform actually
bigstep=0.8
# sum_{i=1}^{n} abs(actual change of angular momentum <Ji> with respect to                   
# initial  configuration) > maxspinchange will  end selfconsistency process
maxspinchange=1e10

[OUTPUT OF PHYSICAL PROPERTIES]
#output of physical properties to compare with experiment
# 1. For thermal expansion and magnetostriction                   
#  how many spinspin correlation functions                    
#  should be calculated 
nofspincorrs=0
# 2. For Neutron Diffraction                  
#  calculation of mxnofhkl strongest reflections
 maxnofhkls=40
#  maximum scattering vector |Q|[1/A] for calculated hkl's
 maxQ=1.8

kmax=0
lmax=0
xstep=1
maxnoftestspincf=1
hmax=0